### ISSUE TITLE
Merge into the original mod

### ISSUE THREAD

**Issue by Willenbrink** [Khaligufzel/CDDA-Sky-Islands#1]
Hey!

Your fork looks like a nice addition. Have you considered opening a PR in the original mod? I would prefer if I don't have to hunt down various improvements in different repositories in the future and this way more people will benefit from your changes.

**Comment by Khaligufzel** [comment]
That's a good idea. I have never done it before though, but let me try!

**Comment by Willenbrink** [comment]
Looks good to me. Thanks a lot and congratulations on opening your first PR!
